### ISSUE TITLE
Errore in "Recenti"

### ISSUE THREAD

**Issue by etnoc94** [nathan990315/MIUI_12_Italy#14]
Ho trovato un piccolo errore in "Recenti". In alto dove c'è lo stato memoria (x.x GB | x.x GB) l'unità di misura della memoria risulta essere x.x GBB | x.x GBB invece di GB. Secondo me l'errore si trova in MiuiSystemUI.apk-> strings.xml alla stringa 1759 "string name="status_bar_recent_memory_info1">%1$sB | %2$sB</string"
Allego anche uno screenshot dell'errore per una miglior comprensione
![IMG_20200619_183826](https://user-images.githubusercontent.com/67161434/85157903-5e79d700-b25c-11ea-9a03-791fcd2dd32f.jpg)

**Comment by BIOLorenz** [comment]
Ciao, farò una ricerca della stringa, entro la prossima settimana dovrebbe essere fixata!
Grazie della segnalazione dettagliata!

Buona serata

**Comment by BIOLorenz** [comment]
Ciao,
è stata corretta la relativa stringa, dovrebbe essere apposto nella prossima release.
Grazie per il feedback!

**Comment by etnoc94** [comment]
Ciao, grazie per la veloce correzione ma soprattutto grazie per il tuo lavoro di mantenimento della traduzione!
Se ci dovesse essere altro non tarderà ad arrivare un mio feedback.
