### ISSUE TITLE
Bluetooth devices status

### ISSUE THREAD

**Issue by justmedoingthings** [nathan990315/MIUI_12_Italy#15]
I was connecting to my computer and noticed that near the status is written activo it should be attivo. Thank you.
![Screenshot_2020-06-30-04-39-57-595_com android settings](https://user-images.githubusercontent.com/67618355/86078206-df6f7480-ba8d-11ea-80f5-84e1cf880a4a.jpg)

**Comment by BIOLorenz** [comment]
Ciao!
Grazie mille per la segnalazione, questo bug spagnolo è stato rimandato al mittente :D -> 371a86d

Troverai molto probabilmente il fix nella build di Venerdì.
P.S: Ho approfittato del tuo screenshot anche per modificare quel "Dispositivi util.....zzati raramente", dovrebbe apparire "Altri dispositivi", più corto e più leggibile. -> 50bc79b

Ciao e buona giornata!
<sub><b>Se vuoi supportare il mio lavoro, offrimi un caffè cliccando sul pulsante "Sponsor" nella home della repository 😄 </b></sub>
