### ISSUE TITLE
Notizie in lingua polacca sul meno di sinistra dalla home....

### ISSUE THREAD

**Issue by hughes8511** [nathan990315/MIUI_12_Italy#16]
Non riesco a capire come impostare la lingua italiana sul menù assistente che si trova dalla home a sinistra (spero si capisca quale intendo) c'è un modo per inserire le notizie in italiano??

**Comment by BIOLorenz** [comment]
Ciao, purtroppo quelle notizie sono limitate dal fatto che la versione xiaomi.eu si basa sulla regione Polacca e non Italiana come la semplice global.
Xiaomi non ha ancora messo a disposizione il modo di modificare la lingua indipendentemente dalla regione impostata.
Un consiglio che posso darti è di utilizzare "Google discover" al posto dell'App Vailt, oppure di disinstallare gli aggiornamenti e tenere la versione "base" senza notizie.

Spero di esserti stato d'aiuto!
Non è considerata una issue, ma tengo aperto in caso tu abbia bisogno di ulteriore aiuto :)

**Comment by hughes8511** [comment]
Grazie mille per la spiegazione ma penso tu l'abbia capito che sono un neofita...😃

**Comment by BIOLorenz** [comment]
> Grazie mille per la spiegazione ma penso tu l'abbia capito che sono un neofita...😃

E che problemi ci sono?
Nessuno nasce imparato, anzi mi ha fatto piacere rispondere alla tua (giusta) segnalazione!

Dopotutto siamo anche qui per questo no? :)

Chiudo la issue per aver chiarito il misfatto! 😁
