### ISSUE TITLE
menu impostazioni chiamate

### ISSUE THREAD

**Issue by PieroAnt** [nathan990315/MIUI_12_Italy#19]
Nelle impostazioni delle chiamate in arrivo nella seconda voce del menù risulta "non vibrare" quando arriva una chiamata, nelle impostazioni in lingua inglese risulta invece: abbassa il volume di una chiamata quando sollevi il telefono. In effetti è quel che succede quando si prende il telefono per rispondere, la suoneria si riduce di livello. Telefono MI9 MIUI 12 20.8.20

**Comment by BIOLorenz** [comment]
Ciao, darò un'occhiata alla traduzione per la prossima release :)

**Comment by PieroAnt** [comment]
Ok. Ciao grazie

Il ven 28 ago 2020, 17:29 Lorenzo <notifications@github.com> ha scritto:

**Comment by PieroAnt** [comment]
Ho notato che il menù è stato sistemato, infatti adesso risulta "Riduci suoneria quando sollevato" rimane soltanto da tradurre la descrizione che è rimasta come prima.

**Comment by PieroAnt** [comment]
![Screenshot_2020-10-16-15-26-57-054_com android phone](https://user-images.githubusercontent.com/70077425/96264452-7a9c4380-0fc4-11eb-9fc7-288dd02e048b.jpg)

**Comment by BIOLorenz** [comment]
Ciao,
ottimo!

Sto allineando un po' di traduzioni quindi vedrò di correggere anche questa. Grazie!
