### ISSUE TITLE
Email App

### ISSUE THREAD

**Issue by patit72** [nathan990315/MIUI_12_Italy#20]
![2020-08-28 17_12_48-MIUI_12_Italy_strings xml at master · nathan990315_MIUI_12_Italy](https://user-images.githubusercontent.com/16647912/91583693-deee3f80-e951-11ea-89e8-4eecf008546b.png)

Se si sceglie di non sincronizzare i contatti, quando compare l'avviso, la parola Contatti contiene la seconda o maiuscola
COntatti

**Comment by BIOLorenz** [comment]
Grazie della segnalazione!
Farò una ricerca nelle stringhe per verificare se COntatti appare anche in altre app.

**Comment by patit72** [comment]
vedi screenshot

**Comment by BIOLorenz** [comment]
Ciao, fix effettuato 665764f4
