### ISSUE TITLE
Hmn8 finestre fluttuanti non funzionano più :(

### ISSUE THREAD

**Issue by hughes8511** [nathan990315/MIUI_12_Italy#23]
Salve come da titolo il problema è che dagli ultimi due aggiornamenti ( Xiaomi.eu MIUI 12 beta con ginkgo non mi funzionano più le finestre cioè non mi dà proprio la possibilità di aprirle non c'è nemmeno la spunta..,ed inoltre noto un leggero rallentamento del sistema più in generale....

**Comment by nathan990315** [comment]
Mi spiace ma questo repository riguarda solo le traduzioni di MIUI EU. Tuttavia ti consiglio di porre la questione sul sito ufficiale. Credo che li ti sapranno aiutare

Il giorno 25 set 2020, alle ore 13:43, hughes8511 <notifications@github.com> ha scritto:

﻿

Salve come da titolo il problema è che dagli ultimi due aggiornamenti ( Xiaomi.eu MIUI 12 beta con ginkgo non mi funzionano più le finestre cioè non mi dà proprio la possibilità di aprirle non c'è nemmeno la spunta..,ed inoltre noto un leggero rallentamento del sistema più in generale....
