### ISSUE TITLE
Gallery is forcibly closing

### ISSUE THREAD

**Issue by robbie2k** [nathan990315/MIUI_12_Italy#24]
I don't know if this is the right section for this feedback, but my gallery is forcibly closing since I have the first picture shot by camera, if the gallery is empty of shot by the camera (i.e. there are only the pictures downloaded by the Mi Account) the gallery is NOT forcibly closing.
This happens in the first and also in the second space.

Xiaomi Mi10 8/256 global version unlocked, with ROM xiaomi.eu_multi_MI10_V12.1.5.0.RJBCNXM_v12-11

**Comment by BIOLorenz** [comment]
Hi,
Is this related to Italian language?

**Comment by robbie2k** [comment]
Seems to be a MIUI bug




Scarica Outlook per Android







On Sun, Oct 11, 2020 at 1:32 PM -0500, "Lorenzo" <notifications@github.com> wrote:















Hi,

Is this related to Italian language?

**Comment by BIOLorenz** [comment]
It's a MIUI bug, try to report the problem on c.mi.com or Xiaomi.eu forum.

You can report only italian translation bugs here
