### ISSUE TITLE
MiCC9e e Google play services per AR

### ISSUE THREAD

**Issue by andrehandong** [nathan990315/MIUI_12_Italy#27]
Ciao Nathan,

sono Andrea e spero di essere nel posto giusto e non disturbare inutilmente.
Come leggi nell'oggetto, sto avendo problemi con un MiCC9e e l'AR di Google.
Ho scaricato l'app da questo articolo

https://www.miui.it/2019/08/27/xiaomi-mi-a3-google-arcore/

perché mi sembra di aver capito che l'A3 è il gemello del CC9e. Sul mio CC9e ho installato l'ultima release settimanale e il problema con AR nasce nel gioco dei Pokémon. Il gioco vede che c'è AR perché spuntano delle opzioni nuove. Nello stesso tempo, però, alcune cose che prima si potevano fare tranquillamente, con AR installato non si possono più fare.

Non essendo del settore non so darti migliori spiegazioni, ma, ovviamente, dimmi pure cosa ti serve e come fare per recuperare le info che ti servono.

Grazie per il lavoro sulle ROM, vanno benissimo.

Ciao, Andrea

**Comment by BIOLorenz** [comment]
Ciao!
Il posto non è quello corretto, qui si parla di traduzioni della rom xiaomi.eu e solo di traduzioni.

Lascio comunque aperta la Issue e la assegno a Nathan, vediamo se sarà in grado di rispondere alla domanda :)

**Comment by andrehandong** [comment]
Come non detto, grazie mille e scusate.

**Comment by andrehandong** [comment]
In merito alla traduzione ho appena notato che, volendo, si potrebbe migliorare la traduzione del menù di scelta di quando si collega il cavo dati con un PC. Al momento mi appaiono "Use USB for" "solo ricarica" "File transfers" "Photo transfers", che a me non danno nessun fastidio, ma magari a qualcuno che non sa l'inglese potrebbero generare problemi (anche se le icone parlano già abbastanza chiaro, direi).

**Comment by BIOLorenz** [comment]
> In merito alla traduzione ho appena notato che, volendo, si potrebbe migliorare la traduzione del menù di scelta di quando si collega il cavo dati con un PC. Al momento mi appaiono "Use USB for" "solo ricarica" "File transfers" "Photo transfers", che a me non danno nessun fastidio, ma magari a qualcuno che non sa l'inglese potrebbero generare problemi (anche se le icone parlano già abbastanza chiaro, direi).

Ciao, riguardo a questo hai perfettamente ragione!
Porta pazienza però perchè siamo praticamente io e Nathan che lavoriamo alla traduzione e il tempo è ben poco per stare dietro alle modifiche di Xiaomi.

Dalla prossima settimana vedrò di prendere per bene le stringhe aggiunte e di tradurle.
Grazie comunque per il feedback!

**Comment by andrehandong** [comment]
Io ho tutta la pazienza che vuoi, davvero. Cerco di scrivere cose inerenti al vero scopo di questo forum, mica cose che non c'entrano nulla come nel primo messaggio.
Un altro miglioramento potrebbe riguardare la voce del menù delle impostazioni "Notifications & Control center", e dentro a questo sottomenù la voce "Item shown on Lock screen after swiping down". 
Ripeto, segnalo solamente per dire qualcosa di attinente, non perché pretenda la correzione e meno che mai l'istantaneità.
Per la storia dell'AR sapete per caso dirmi dove trovare gli svilupattori della ROM?

PS: avete bisogno di personale italiano che parli cinese?

**Comment by nathan990315** [comment]
Ciao scusa la risposta in ritardo, per quanto riguarda le funzionalità AR le rom si appoggiano al google play service for AR, perciò non posso fare molto per risolvere il problema...
Mi potresti indicare esattamente da quando noti questi problemi? hai avuto problemi dopo l'aggiornamento della rom? 
il servizio google play service for AR è aggiornato? 
Se mi dai la versione della rom che attualmente hai installato posso provare a verificare con il team dev che si occupa di sviluppare le rom.

**Comment by andrehandong** [comment]
Dunque, cerco di spiegarmi meglio.
L'AR non è mai stata installata nel telefono. Io l'ho installata solo perché ho letto in un sito che riguarda l'app dei Pokémon che per sfruttare a pieno il gioco serve l'AR. Poi, non posso installare l'AR direttamente dal Play Store perché mi dice che il telefono non la supporta (non è venduto in Italia), ma sapendo che MiCC9e e MiA3 sono gemelli (forse quello che so è sbagliato, forse è proprio qui l'errore) ho scaricato l'app AR da questo link https://www.miui.it/2019/08/27/xiaomi-mi-a3-google-arcore/ . La ROM installata è quella dell'11/11/2020, l'ultima disponibile, ma il problema c'era già con le versioni precedenti (installo quasi tutte le settimane l'ultima release). In concreto succede questo: nel gioco ci sono delle missioni per guadagnare delle risorse; una di queste prevedere la registrazione di un video di un determinato luogo; senza l'AR non posso fare questo video, mentre con l'AR sì; il fatto è che con l'AR, però, non posso più intaragire con il Pokémon amico, cioè l'animeletto di cui dovrei prendermi cura ogni giorno sempre per ottenere dei bonus. Questo è quanto. Se c'è da aggiungere altro, chiedi pure (volendo potrei direttamente parlare con gli sviluppatori, così evito di stressarti senza motivo). Allego i dati del telefono.
Grazie in tutti i casi.
[DroidInfo.pdf](https://github.com/nathan990315/MIUI_12_Italy/files/5547169/DroidInfo.pdf)
