### ISSUE TITLE
Varie traduzioni sbagliate

### ISSUE THREAD

**Issue by n0tfilzhang** [nathan990315/MIUI_12_Italy#28]
1. (Fixed)
Problematica: "Notifications & Control center"
Applicazione: Impostazioni
Versione: 20.12.9
Dispositivo: lavender (RN7)
Suggerimento: "Notifiche e Centro di controllo"
2.
Problematica: "Tap fingerprint sensor to wake" "Wake screen when no fingerprints have been enrolled"
Applicazione: Impostazioni > Schermata di blocco
Versione: 20.12.9
Dispositivo: lavender (RN7)
Suggerimento: "Tocca il sensore d'impronte per risvegliare" "Risveglia lo schermo quando nessuna impronta è stata registrata"
3. (Fixed)
Problematica: "Arrange items in Recents" "Vertically" "Horizontally"
Applicazione: Impostazioni > Schermata home
Versione: 20.12.9
Dispositivo: lavender (RN7)
Suggerimento: "Stile applicazioni recenti" "Verticalmente" "Orizzontalmente"
4. (Fixed)
Problematica: "Light Mode"
Applicazione: Impostazioni > Schermo
Versione: 20.12.9
Dispositivo: lavender (RN7)
Suggerimento: "Modalità chiara"
5. (Fixed)
Problematica: "More dark mode options"
Applicazione: Impostazioni > Schermo
Versione: 20.12.9
Dispositivo: lavender (RN7)
Suggerimento: "Più opzioni modalità scura"
6. (Fixed)
Problematica: "Allow all rotations"
Applicazione: Impostazioni > Schermo
Versione: 20.12.9
Dispositivo: lavender (RN7)
Suggerimento: "Consenti tutte le rotazioni"
7. (Fixed)
Problematica: "Adjust text and backgrounds automatically"
Applicazione: Impostazioni > Schermo > More Dark mode options
Versione: 20.12.9
Dispositivo: lavender (RN7)
Suggerimento: "Regola testo e backgrounds automaticamente"
8. (Fixed)
Problematica:  "Individual apps"
Applicazione: Impostazioni > Schermo > More Dark mode options
Versione: 20.12.9
Dispositivo: lavender (RN7)
Suggerimento: "App individuali"
9. (Fixed)
Problematica: "Notification shade"
Applicazione: Impostazioni > Notifications & Control center
Versione: 20.12.9
Dispositivo: lavender (RN7)
Suggerimento: "Pannello delle notifiche"
10. (Fixed)
Problematica: "Items shown on the Lock screen after swiping down"
Applicazione: Impostazioni > Notifications & Control center
Versione: 20.12.9
Dispositivo: lavender (RN7)
Suggerimento: "Elementi mostrati nella Schermata di Blocco dopo aver trascinato giù"
11. (Fixed)
Problematica: "Works with the new version of Control center"
Applicazione: Imposrazioni > Notifications & Control center > Items shown on the Lock screen after swiping down
Versione: 20.12.9
Dispositivo: lavender (RN7)
Suggerimento: "Funziona con la nuova versione del Centro di controllo"
12. (Fixed)
Problematica: "Gesture shortcuts"
Applicazione: Impostazioni > Impostazioni aggiuntive
Versione: 20.12.9
Dispositivo: lavender (RN7)
Suggerimento: "Scorciatoie gesture"
13. (Fixed)
Problematica: "Show wheater info"
Applicazione: Impostazioni > Notifications & Control center > Notification shade
Versione: 20.12.9
Dispositivo: lavender (RN7)
Suggerimento: "Mostra informazioni meteo"
14. (Fixed)
Problematica: "Fix n. battery usage issues"
Applicazione: Sicurezza > Batteria
Versione: 20.12.9
Dispositivo: lavender (RN7)
Suggerimento: "Correggi n. problemi di utilizzo della batteria"
15. (Fixed)
Problematica: "Battery usage" "Charged today" "n. times"
Applicazione: "Impostazioni > Batteria > Batteria (Accanto a Risparmio batteria)
Versione: 20.12.9
Dispositivo: lavender (RN7)
Suggerimento: "Utilizzo della batteria" "Caricata oggi" "n. volte"
16. (Fixed)
Problematica: "Clear data"
Applicazione: Registratore > Impostazioni
Versione: 20.12.9
Dispositivo: lavender (RN7)
Suggerimento: "Cancella dati"
17. 
Problematica: "Text input" "Select gesture for activating text input when TalkBack is on"
Applicazione: Impostazioni > Impostazioni aggiuntive > Accessibilità > Vista
Versione: 20.12.9
Dispositivo: lavender (RN7)
Suggerimento: "Inserimento testo" "Seleziona gesture per attivare inserimento testo quando TalkBack è attivo"
18. (Fixed)
Problematica: "Learn more about User Experience Program"
Applicazione: Impostazzioni > Password e sicurezza > Privacy
Versione: 20.12.9
Dispositivo: lavender (RN7)
Suggerimento: "Saperne di più sul Programma Esperienza Utente"

Aggiornamento 8/1/21, Dispositivo: lavender (RN7), Versione: 21.1.6
19. (Fixed)
Problematica: Wallpaper & personalization
Applicazione: Impostazioni
Suggerimento: Sfondo e personalizzazione
20.
Problematica: "Font settings" "Fonts and text size"
Applicazione: Impostazioni > Schermo
Suggerimento: "Impostazioni font" "Fonts e dimensione testo"
21. 
Problematica: "Select style and adjust size"
Applicazione: Impostazioni > Schermata home
Suggerimento: "Seleziona stile e regola dimensione"
22. (Fixed)
Problematica: "Awerness"
Applicazione: Impostazioni > Protezione privacy
Suggerimento: -
23. (Fixed)
Problematica: "Protection"
Applicazione: Impostazioni > Protezione privacy
Suggerimento: "Protezione"
24. (Fixed)
Problematica: "View all app behavior"
Applicazione: Impostazioni > Protezione privacy
Suggerimento: "Visualizza comportamenti app"
25. (Fixed)
Problematica: "Protected"
Applicazione: Impostazioni > Protezione privacy
Suggerimento: "Protetto"
26. (Fixed)
Problematica: "Protect clipboard"
Applicazione: Impostazioni > Protezione privacy > Privacy
Suggerimento: "Proteggi gli appunti"
27. (Fixed)
Problematica: "Detect privacy risks" "Detect privacy risks automatically and receive recommendations about protection measures"
Applicazione: Impostazioni > Protezione privacy > Privacy
Suggerimento: "Individua rischi privacy" "Individua automaticamente i rischi privacy e ricevi suggerimenti sulle misure di protezione"
28. (Fixed)
Problematica: "Record all app behavior"
Applicazione: Impostazioni > Protezione privacy > Privacy
Suggerimento: "Registra tutti i comportamenti delle app"
29. (Fixed)
Problematica: "Private space"
Applicazione: Impostazioni > Protezione privacy > Protection 
Suggerimento: "Spazio privato"
30. (Fixed)
Problematica: "To protect your privacy, MIUI allows you to control how apps access your photos and social media chat history"
Applicazione: Impostazioni > Protezione privacy > Protection > Private space
Suggerimento: "Per proteggere la tua privacy, MIUI ti consente ti controllare il modo in cui le app accedono alle tue foto e alle conversazioni chat dei social media"
31. (Fixed)
Problematica: "Encrypt and protect items with a screen lock"
Applicazione: Impostazioni > Protezione privacy > Private space 
Suggerimento: "Cripta e proteggi gli elementi con un blocco schermo"
32. (Fixed)
Problematica: "Comprehensive privacy protection"
Applicazione: Impostazioni > Protezione privacy > Privacy
Suggerimento: "Protezione completa della privacy"
33. (Fixed)
Problematica: "Protect Gallery and social media apps" "Select which apps are allowed to access your photos, videos, and chat histroy"
Applicazione: Impostazioni > Protezione privacy > Intercettazione di rete
Suggerimento: "Proteggi la Galleria e le app di social media" "Seleziona quali app possono accedere alle tue foto, video e conversazioni chat"
33. (Fixed)
Problematica: "Share photos without location info and metadata"
Applicazione: Impostazioni > Protezione privacy > Intercettazione di rete 
Suggerimento: "Condividi le foto senza info sulla posizione e metadati"
34. (Fixed) 
Problematica: "Allow apps to use permissions only while you're using the app" "To prevent an app from using permissions in the background, you can allow to use the permissions related to location, recording audio, and contacts only while you're using the app"
Applicazione: Impostazioni > Protezione privacy > Intercettazione di rete
Suggerimento: "Permetti alle app di utilizzare i permessi soltanto quando stai utilizzando l'app" "Per impedire a un'app di utilizzare i permessi in background, puoi permettere di utilizzare i permessi relativi alla posizione, registrazione audio e contatti soltanto quando stai utilizzando l'app"
35. (Fixed) 
Problematica: "Allow apps to use permissions once" "You can allow to use the permissions related to location, recording audio, and contacts only once. These permissions will be restricted again shortly after the app is closed"
Applicazione: Impostazioni > Protezione privacy > Intercettazione di rete
Suggerimento: "Permetti alle app di utilizzare i permessi una volta" "Puioi permettere di utilizzare i permessi relativi alla posizione, registrazione audio e contatti soltanto una volta. Questi permessi verranno limitati nuovamente poco dopo la chiusura dell'app"
36. (Fixed)
Problematica: "Restrict chain start"
Applicazione: Impostazioni > Protezione privacy > Intercettazione di rete
Suggerimento: -
37. (Fixed)
Problematica: "Restrict using camera in the background"
Applicazione: Impostazioni > Protezione privacy > Intercettazione di rete
Suggerimento: "Limita l'utilizzo della fotocamera in background"
38. (Fixed)
Problematica: "Grant permissions but give apps blank files instead of personal info"
Applicazione: Impostazioni > Protezione privacy > Intercettazione di rete
Suggerimento: "Consenti i permessi ma dai alle app file vuoti invece delle informazioni personali"

**Comment by BIOLorenz** [comment]
Ciao!
Grazie per il suggerimento, purtroppo al momento siamo praticamente solo 2 persone che stanno lavorando al progetto.

Io sinceramente sono rimasto indietro con le build ma in questi giorni ho ripreso a tradurre tutte le stringhe mancanti, nelle prossime build troverai sicuramente queste stringhe fixate! ;)
