### ISSUE TITLE
Vari Bug Traduzione

### ISSUE THREAD

**Issue by francescobenenati** [nathan990315/MIUI_12_Italy#30]
Buongiorno, Vi segnalo alcuni bug presenti sulla weekly 21.1.20 sul MI 10 (UMI) in moda da aiutarvi nelle correzioni. In grassetto i bug:

1.  Sulla schermata di blocco con ND attivo: "**DND Is ON, Notifications and calls Will be silencied.  Turn Off**" Dovrebbe essere "ND attivo. Le notifiche e le chiamate verranno silenziate. Disattiva"

2. ~~All'attivazione della modalità silenziosa tramite Toogle sulla barra di stato o tramite il bilanciere: "**ND attivato. Suonerie per le chiamate e notifiche silenziate.**" dovrebbe essere "Silenzioso attivato" o "Modalità silenziosa attivata" e non "ND attivato".~~     _**Non più presente dalla build 21.04.08**_

~~3.  Notifiche e centro di controllo> Schermata di blocco: "**Formatto**" invece di "Formato".~~ _**Fixato**_

4. Notifiche e centro di controllo> Panello delle notifiche: "**Dispositivo MIUI**" dovrebbe essere "Android" 

5. Schermo: "**Font settings**" dovrebbe essere "Impostazioni Font"

6. Schermo > Contrasto e Colori: 

~~- "**Saturated**" dovrebbe essere "Saturi" o " "Vividi"~~
~~- "**Original color: restore standard color of screen content with color calibration.**" dovrebbe essere: "Colore originale: Ripristina i colori standard dei contenuti a schermo secondo la calibrazione dei colori."~~        _**Fixati**_

7. Suoni e vibrazione: 

- alla voce silenzia il volume multimediale in modalità silenziosa viene riportato "**games, music,videos and other apps**" dovrebbe essere "giochi, musica, video e altre applicazioni".
- **Silenzioso Temporizzato** dovrebbe essere "Non Disturbare temporizzato" o "Schedula Non Disturbare".

~~- **Lista Vip** secondo me è poco chiaro. Secondo la traduzione presente sulla global dovrebbe essere: "Consenti le chiamate in entrata"~~           _**Non più presente dalla build 21.04.08**_
~~- Sulla scheda notifiche in alto appare una descrizione in inglese: "**We've explored different ecosystems and recreated their distinct sounds. Start exploring the sounds of nature with us**" dovrebbe essere "Abbiamo esplorato diversi ecosistemi e ricreato i loro suoni distintivi. Inizia a esplorare i suoni della natura con noi".~~       _**Fixato**_

~~8. Always on e schermata di sblocco > effetto notifiche: "**Non pulire niente**" dovrebbe essere qualcosa del tipo "Nessun azione"~~           _**Fixato**_

Grazie per il lavoro svolto.

**Comment by BIOLorenz** [comment]
> Buongiorno, Vi segnalo alcuni bug presenti sulla weekly 21.1.20 sul MI 10 (UMI) in moda da aiutarvi nelle correzioni. In grassetto i bug:
> 
~~1. Sulla schermata di blocco con ND attivo: "**DND Is ON, Notifications and calls Will be silencied.  Turn Off**" Dovrebbe essere "ND attivo. Le notifiche e le chiamate verranno silenziate. Disattiva"~~
~~2. All'attivazione della modalità silenziosa tramite Toogle sulla barra di stato o tramite il bilanciere: "**ND attivato. Suonerie per le chiamate e notifiche silenziate.**" dovrebbe essere "Silenzioso attivato" o "Modalità silenziosa attivata" e non "ND attivato".~~
> 
> ~3. Notifiche e centro di controllo> Schermata di blocco: "**Formatto**" invece di "Formato".~ _**Fixato**_
> 
> ~1. Notifiche e centro di controllo> Panello delle notifiche: "**Dispositivo MIUI**" dovrebbe essere "Android"~
> ~2. Schermo: "**Font settings**" dovrebbe essere "Impostazioni Font"~
> ~3. Schermo > Contrasto e Colori:~
> 
> ~- "**Saturated**" dovrebbe essere "Saturi" o " "Vividi"~
> ~- "**Original color: restore standard color of screen content with color calibration.**" dovrebbe essere: "Colore originale: Ripristina i colori standard dei contenuti a schermo secondo la calibrazione dei colori."~ _**Fixati**_
> 
> 1. Suoni e vibrazione:
> 
> * alla voce silenzia il volume multimediale in modalità silenziosa viene riportato "**games, music,videos and other apps**" dovrebbe essere "giochi, musica, video e altre applicazioni".
> ~* **Silenzioso Temporizzato** dovrebbe essere "Non Disturbare temporizzato" o "Schedula Non Disturbare".~
> 
> ~- **Lista Vip** secondo me è poco chiaro. Secondo la traduzione presente sulla global dovrebbe essere: "Consenti le chiamate in entrata"~ _**Non più presente dalla build 21.04.08**_
> ~- Sulla scheda notifiche in alto appare una descrizione in inglese: "**We've explored different ecosystems and recreated their distinct sounds. Start exploring the sounds of nature with us**" dovrebbe essere "Abbiamo esplorato diversi ecosistemi e ricreato i loro suoni distintivi. Inizia a esplorare i suoni della natura con noi".~ _**Fixato**_
> 
> ~8. Always on e schermata di sblocco > effetto notifiche: "**Non pulire niente**" dovrebbe essere qualcosa del tipo "Nessun azione"~ _**Fixato**_
> 
> Grazie per il lavoro svolto.

Apparentemente manca solo
Suoni e vibrazione:
alla voce silenzia il volume multimediale in modalità silenziosa viene riportato "games, music,videos and other apps" dovrebbe essere "giochi, musica, video e altre applicazioni".

Verrà fixato settimana prossima credo :)

**Comment by francescobenenati** [comment]
> > Buongiorno, Vi segnalo alcuni bug presenti sulla weekly 21.1.20 sul MI 10 (UMI) in moda da aiutarvi nelle correzioni. In grassetto i bug:
> 
> ~1. Sulla schermata di blocco con ND attivo: "**DND Is ON, Notifications and calls Will be silencied. Turn Off**" Dovrebbe essere "ND attivo. Le notifiche e le chiamate verranno silenziate. Disattiva"~
> ~2. All'attivazione della modalità silenziosa tramite Toogle sulla barra di stato o tramite il bilanciere: "**ND attivato. Suonerie per le chiamate e notifiche silenziate.**" dovrebbe essere "Silenzioso attivato" o "Modalità silenziosa attivata" e non "ND attivato".~
> 
> > ~3. Notifiche e centro di controllo> Schermata di blocco: "**Formatto**" invece di "Formato".~ _**Fixato**_
> > ~1. Notifiche e centro di controllo> Panello delle notifiche: "**Dispositivo MIUI**" dovrebbe essere "Android"~
> > ~2. Schermo: "**Font settings**" dovrebbe essere "Impostazioni Font"~
> > ~3. Schermo > Contrasto e Colori:~
> > ~- "**Saturated**" dovrebbe essere "Saturi" o " "Vividi"~
> > ~- "**Original color: restore standard color of screen content with color calibration.**" dovrebbe essere: "Colore originale: Ripristina i colori standard dei contenuti a schermo secondo la calibrazione dei colori."~ _**Fixati**_
> > 
> > 1. Suoni e vibrazione:
> > 
> > 
> > * alla voce silenzia il volume multimediale in modalità silenziosa viene riportato "**games, music,videos and other apps**" dovrebbe essere "giochi, musica, video e altre applicazioni".
> >   ~* **Silenzioso Temporizzato** dovrebbe essere "Non Disturbare temporizzato" o "Schedula Non Disturbare".~
> > 
> > ~- **Lista Vip** secondo me è poco chiaro. Secondo la traduzione presente sulla global dovrebbe essere: "Consenti le chiamate in entrata"~ _**Non più presente dalla build 21.04.08**_
> > ~- Sulla scheda notifiche in alto appare una descrizione in inglese: "**We've explored different ecosystems and recreated their distinct sounds. Start exploring the sounds of nature with us**" dovrebbe essere "Abbiamo esplorato diversi ecosistemi e ricreato i loro suoni distintivi. Inizia a esplorare i suoni della natura con noi".~ _**Fixato**_
> > ~8. Always on e schermata di sblocco > effetto notifiche: "**Non pulire niente**" dovrebbe essere qualcosa del tipo "Nessun azione"~ _**Fixato**_
> > Grazie per il lavoro svolto.
> 
> Apparentemente manca solo
> Suoni e vibrazione:
> alla voce silenzia il volume multimediale in modalità silenziosa viene riportato "games, music,videos and other apps" dovrebbe essere "giochi, musica, video e altre applicazioni".
> 
> Verrà fixato settimana prossima credo :)

Manca anche: "Silenzioso Temporizzato dovrebbe essere "Non Disturbare temporizzato" o "Schedula Non Disturbare"." 

Ottimo lavoro con la traduzione, la build di questa settimana è davvero ottima dal punto di vista della traduzione :) Ho trovato qualche descrizione e nuova stringa in inglese, quando ho un po' di tempo provvederò a segnalarle con un'altra issue, nel frattempo ancora grazie!
