### ISSUE TITLE
He

### ISSUE THREAD

**Issue by hman688** [nathan990315/MIUI_12_Italy#33]
When I use italia language pack to add for miui rom. An error has occurred.
[system_app_crash@160246_08022021.txt](https://github.com/nathan990315/MIUI_12_Italy/files/5942904/system_app_crash%40160246_08022021.txt)

**Comment by hman688** [comment]
[system_app_crash@160246_08022021.txt](https://github.com/nathan990315/MIUI_12_Italy/files/5943166/system_app_crash%40160246_08022021.txt)

**Comment by nathan990315** [comment]
Il problema ti si presenta ancora?

**Comment by BIOLorenz** [comment]
Riferimento a MIUI V9
