### ISSUE TITLE
Problemi di traduzione / Translation issues

### ISSUE THREAD

**Issue by mind-overflow** [nathan990315/MIUI_12_Italy#34]
### Problema 1 / Problem 1
Il testo della modalità "silenziosa" va a capo per un singolo carattere, ed è brutto. I miei consigli sono:
  - tenere come testo "Silenz." con il punto finale;
  - metterlo in inglese, ovvero "Silent", anche se sarebbe errato perché stiamo parlando della versione italiana;
  - usare una sigla come "ND" (DND in inglese) per "Non disturbare", del tipo "SLZ".

The "Silent" mode text goes in a new line only for a single letter, and looks ugly. Suggested solutions are:
  - only keep "Silenz." with a final dot;
  - use it in english: "Silent". This, however, is probably unacceptable as we are talking about the Italian translation;
  - use an acronym, such as "SLZ", like we already do with "DND" for "Do Not Disturb".

<details>
  <summary>Immagine / Image</summary>

  ![1613225016346](https://user-images.githubusercontent.com/67104846/107851859-44a18b80-6e0d-11eb-9444-de74729167d9.jpg)

</details>

### Problema 2 / Problem 2
Nell'app "schermo acceso", le ore e i minuti non sono separati da uno spazio. Questo appare sia nell'intestazione che nella lista app.
In the "screen time" app, hours and minutes are not separated by space. This happens both in the header and in the app list.

<details>
  <summary>Immagini / Images</summary>

  ![1613225016199](https://user-images.githubusercontent.com/67104846/107851777-b6c5a080-6e0c-11eb-9ec1-9c262adb4340.jpg)
  ![1613225016050](https://user-images.githubusercontent.com/67104846/107851773-b0cfbf80-6e0c-11eb-9259-60fecea4086b.jpg)

</details>

### Dettagli / Details
Questi problemi si stanno verificando con un Mi 9T Pro; Xiaomi.eu build del 4 febbraio 2021 (21.2.3 Beta).
These issues are present with a Mi 9T Pro; Xiaomi.eu built on 4th February, 2021 (21.2.3 Beta).

### PS / Final notes
Ho notato, nei commenti di un'altra issue, che siete solo in due e state avendo difficoltà nello stare dietro alle build. Se vi dovesse servire una mano, oltre a creare semplici issues potrei benissimo aiutare collaborando! Non ho mai fatto questo lavoro in particolare con Android ma sono uno sviluppatore, per cui una volta capito il procedimento di estrazione delle stringhe non ho problemi a continuare.

**Comment by mind-overflow** [comment]
Un altro punto in cui a mio parere le traduzioni non sono ottimali:

<details>
  <summary>Immagine</summary>

  ![image](https://user-images.githubusercontent.com/67104846/107862655-6838f600-6e4e-11eb-9689-f536ae230c11.png)

</details>

Questa notifica appare non appena il telefono raggiunge il 60% di carica: il risparmio energetico viene disattivato automaticamente. Quindi, io sostituirei con:

Risparmio energetico disattivato.
La batteria ha raggiunto il 60% (+ "di carica"?).

**Comment by nathan990315** [comment]
Grazie verifico le stringe e correggo

**Comment by mind-overflow** [comment]
> Grazie verifico le stringe e correggo

Ottimo! Grazie mille.

**Comment by mind-overflow** [comment]
Se possibile, farei un'ulteriore aggiunta.
Nell'app Orologio, quando si tocca su una sveglia.
Modificherei "Impostazioni addizionali" con semplicemente "Impostazioni", dato che il testo non ci sta nella casella e comunque "addizionali" è ridondante.

![image](https://user-images.githubusercontent.com/67104846/107880489-518eaf80-6edf-11eb-91f1-a4db8b73ff63.png)

**Comment by nathan990315** [comment]
Prendo nota grazie per queste segnalazioni, le correzioni verranno implementate nelle prossime build dopo il capodanno cinese

**Comment by mind-overflow** [comment]
Ok ottima notizia, grazie ancora! A questo punto segnalo un altro bug che ho trovato, quando si ha la modalità non disturbare attiva. La notifica rimane in inglese anche se il telefono è in italiano.
![Screenshot_2021-02-21-18-10-55-288_lockscreen.jpg](https://user-images.githubusercontent.com/67104846/108632644-54098000-7470-11eb-8275-1a2b942cc7f4.jpg)
Tradurrei con:
```
ND è attivo.
Chiamate e notifiche verranno silenziate.
```

**Comment by mind-overflow** [comment]
Altro piccolo errore: quando si disattiva la modalità silenziosa, appare una notifica che dice "ND attivato. Suonerie per le chiamate e notifiche silenziate." Invece dovrebbe dire "Silenzioso attivato".

<details>
  <summary>Quando attivo ND...</summary>
  
![1613929787159](https://user-images.githubusercontent.com/67104846/108633676-be70ef00-7475-11eb-81d8-e74952b540b0.jpg)

</details>

<details>
  <summary>Quando disattivo il silenzioso...</summary>
  
![1613929787176](https://user-images.githubusercontent.com/67104846/108633697-d9dbfa00-7475-11eb-812b-c33520e461b5.jpg)

</details>

<details>
  <summary>BUG: Quando attivo il silenzioso...</summary>
  
![1613929787140](https://user-images.githubusercontent.com/67104846/108633689-cc267480-7475-11eb-978c-1e5b99c6bfcd.jpg)

</details>

**Comment by mind-overflow** [comment]
Altro problema: quando si seleziona una foto nella galleria e si clicca "aggiungi all'album", l'app chiede se vogliamo copiarla o spostarla in quell'album. Le scelte, però, sono poste in inglese: Move (Sposta) e Copy (Copia).

![Screenshot_2021-02-22-00-33-09-914_com.miui.gallery.jpg](https://user-images.githubusercontent.com/67104846/108642506-bfba1000-74a5-11eb-80c9-771512b2e6e8.jpg)

**Comment by Asharpener** [comment]
Segnalo due problemi di traduzione:
**1. Suoni di notifica animali**
Impostazioni > Suoni e vibrazione > Notifiche
Quando si impostano i suoni di notifica naturali alcuni nomi di animali sono tradotti, altri no. Per esempio "Cheetah" (Ghepardo) o "Hippo" (Elefante)
(anche nelle immagini sono solo alcuni esempi, non tutti gli errori)

<details>
<summary> Immagini</summary>
 
![image](https://user-images.githubusercontent.com/79587627/109072160-e9b54180-76f4-11eb-8b9e-03b7956e239c.png)
![image](https://user-images.githubusercontent.com/79587627/109072443-54667d00-76f5-11eb-8a14-8307ba2f840f.png)

</details>

**2. Google Home sul control center**
Ho scaricato google home e mi è apparso questo riquadro sul control center ma la frase non è tradotta... dovrebbe essere "Scegli un'applicazione per controllare la tua smart home"
<details>
<summary> Immagine</summary>

![image](https://user-images.githubusercontent.com/79587627/109073138-49f8b300-76f6-11eb-9094-3c4d41edf676.png)

</details>

**Comment by mind-overflow** [comment]
> Segnalo due problemi di traduzione:
> **1. Suoni di notifica animali**
> Impostazioni > Suoni e vibrazione > Notifiche
> Quando si impostano i suoni di notifica naturali alcuni nomi di animali sono tradotti, altri no. Per esempio "Cheetah" (Ghepardo) o "Hippo" (Elefante)
> (anche nelle immagini sono solo alcuni esempi, non tutti gli errori)
> 

Aggiungerei che nella descrizione in alto la frase finisce in "fino..."

**Comment by mind-overflow** [comment]
Trovata altra piccola mancanza. Le frasi sono solo in inglese. Per arrivare qui bisogna: aprire control center -> tenere premuto sull'utilizzo dati -> toccare la rotellina in alto a destra -> toccare "Limite dati mobili".

Tradurrei con "Mensile / Illimitato / Giornaliero"; credo che includere anche "Piano" ("Piano mensile / Piano illimitato / Piano giornaliero") sia ridondante e probabilmente non ci sarebbe comunque abbastanza spazio nella casella.  

<details>
  <summary>Immagine</summary>
  
![1614205415515](https://user-images.githubusercontent.com/67104846/109074717-64cc2700-76f8-11eb-9335-f85b580c073b.jpg)

</details>

**Comment by mind-overflow** [comment]
Trovati altri due.
Entrambi sono nell'opzione "Trova Dispositivo" del Mi Cloud, accessibile dalle impostazioni, anche se credo queste stringhe siano usate anche altrove poiché sono molto generiche.

Il primo problema è quando si tenta di disattivare il tracciamento del dispositivo. La seconda opzione letteralmente non ha senso: cosa significa "Disattiva non presente"? quando lo clicco, viene disattivato senza problemi.

![Screenshot_2021-02-25-00-53-40-601_com.miui.cloudservice.jpg](https://user-images.githubusercontent.com/67104846/109082488-626fca00-7704-11eb-8c01-a94522ea1543.jpg)

Il secondo problema è nel "footer" che si legge quando l'opzione è attivata:

"here" dovrebbe essere tradotto con "qui", e la frase dovrebbe essere "....puoi trovare qui", non ".... puoi trovare SU qui".

![Screenshot_2021-02-25-00-54-40-147_com.miui.cloudservice.jpg](https://user-images.githubusercontent.com/67104846/109082619-9c40d080-7704-11eb-9630-7767a0787c50.jpg)

**Comment by mind-overflow** [comment]
Trovato altro problema nel control center... La data si spezza su due linee e quindi sposta anche lo spacing dei bottoni affianco. Allego screenshot in inglese (mostrato correttamente) e italiano.

![IMG_20210225_135040.jpg](https://user-images.githubusercontent.com/67104846/109156144-cb8d2700-7770-11eb-9e29-7ce9c7f7a693.jpg)

![IMG_20210225_135138.jpg](https://user-images.githubusercontent.com/67104846/109156161-ce881780-7770-11eb-9ca3-ec61e5f824b0.jpg)

Ovviamente il suggerimento è di abbreviare:

```
Gio 25 Feb
```

**Comment by mind-overflow** [comment]
Lo stesso accade nella parte delle notifiche: non c'è abbastanza spazio per leggere la temperatura.

![IMG_20210225_135643.jpg](https://user-images.githubusercontent.com/67104846/109156588-4eae7d00-7771-11eb-9a28-3fd1955470b8.jpg)

**Comment by mind-overflow** [comment]
Altro bug per quanto riguarda il Mi Cloud: non c'è abbastanza spazio per tutto il testo nel bottone. Lascerei semplicemente "Pausa" o "Metti in pausa".

Questo si verifica quando la galleria sta venendo sincronizzata col il cloud.

![IMG_20210225_132418.jpg](https://user-images.githubusercontent.com/67104846/109156654-60902000-7771-11eb-9457-f6cb2f5ca674.jpg)

**Comment by mind-overflow** [comment]
> Prendo nota grazie per queste segnalazioni, le correzioni verranno implementate nelle prossime build dopo il capodanno cinese

Appena installata la 21.2.24, ho notato che nemmeno le prime segnalazioni sono state modificate. Non c'è nessuna fretta né problema, ma se serve una mano posso aiutare!

**Comment by mind-overflow** [comment]
Altro problema... Il nome del mese di Marzo ha anche la A maiuscola. Questo accade in diversi punti: le notifiche, il widget meteo, il control center...

![IMG_20210301_094204.jpg](https://user-images.githubusercontent.com/67104846/109472455-6f791a00-7a72-11eb-8615-42e4609129cc.jpg)

![IMG_20210301_094217.jpg](https://user-images.githubusercontent.com/67104846/109472464-72740a80-7a72-11eb-840e-b5e8e0638651.jpg)

**Comment by mind-overflow** [comment]
è passato un mese e due build... ci sono novità?

**Comment by BIOLorenz** [comment]
> è passato un mese e due build... ci sono novità?

Ciao,
da quanto ho visto @nathan990315 ci sta lavorando su, io sono stato impegnato in altro e purtroppo non ho dedicato molto tempo alle traduzioni.
Garantisco che ci daremo un'occhiata al più presto e ti chiedo di aver pazienza, le traduzioni sono un extra della nostra normale vita quotidiana a vedrai che sistemeremo tutto, i Cinesi sono veloci ad aggiungere e rimuovere funzionalità alla Miui e le traduzioni sono centinaia o più da fare ogni build. Grazie per la pazienza :)

**Comment by mind-overflow** [comment]
Certo, ci mancherebbe. Non c'è nessuna fretta, ovviamente abbiamo tutti una vita e degli impegni e questo non è un lavoro a tempo pieno. Mi stava semplicemente venendo un dubbio perché non ricevo risposta da 20 giorni ahah.

**Comment by Sightrasher** [comment]
Segnalo alcuni errori di traduzione, come il formato della data nel Control Center, il mese di Marzo che ha la A maiuscola, e il Quick Menù del Meteo, che riporta "previsine" anziché "previsione" 
![IMG_20210312_210714](https://user-images.githubusercontent.com/64266967/110993249-56783f00-8377-11eb-8613-b4faf0485b64.jpg)
![IMG_20210312_210734](https://user-images.githubusercontent.com/64266967/110993251-57a96c00-8377-11eb-8829-cf7ace546358.jpg)
![IMG_20210312_210754](https://user-images.githubusercontent.com/64266967/110993252-57a96c00-8377-11eb-9ba2-9932998205e8.jpg)

**Comment by BIOLorenz** [comment]
Inizio a lavorare sulle traduzioni Mancanti/Errate, dovrebbero essere visibili entro 1 o 2 build (escluse quelle di questa settimana). Provvedo ad aggiornare la Issue con eventuali fix e Milestones.

**Comment by francescobenenati** [comment]
Buongiorno,
Se posso segnalo anche un piccolissimo errore nel popup di connessione della Mi air 2.
![photo5954272411698443467](https://user-images.githubusercontent.com/51385837/111621413-41bd0080-87e8-11eb-85e2-ad61608f74a1.jpg)

Inoltre, se vi può essere utile, qualche mese fa avevo aperto un thread con alcune segnalazioni di errori/miglioramenti. Alcune di esse sono già state segnalate anche in questo thread. 

Grazie per il vostro lavoro.

**Comment by BIOLorenz** [comment]
Certo, grazie mille!
Meglio che mi tiri su le maniche perché c'è un bel po' da sistemare oltre a quello segnalato da tutti voi🤣

Siete fondamentali per una Miui tradotta al meglio!

**Comment by BIOLorenz** [comment]
> ### Problema 1 / Problem 1
> Il testo della modalità "silenziosa" va a capo per un singolo carattere, ed è brutto. I miei consigli sono:
> 
> * tenere come testo "Silenz." con il punto finale;
> * metterlo in inglese, ovvero "Silent", anche se sarebbe errato perché stiamo parlando della versione italiana;
> * usare una sigla come "ND" (DND in inglese) per "Non disturbare", del tipo "SLZ".
> 
> The "Silent" mode text goes in a new line only for a single letter, and looks ugly. Suggested solutions are:
> 
> * only keep "Silenz." with a final dot;
> * use it in english: "Silent". This, however, is probably unacceptable as we are talking about the Italian translation;
> * use an acronym, such as "SLZ", like we already do with "DND" for "Do Not Disturb".


Ciao, sto iniziando ad applicare i fix e le nuove traduzioni che sono uscite.
Per il momento ho sostituito Silenzioso con **Silenzia**, ti aggiorno sulle altre modifiche mano a mano che le gestisco.

**Comment by BIOLorenz** [comment]
> Segnalo alcuni errori di traduzione, come il formato della data nel Control Center, il mese di Marzo che ha la A maiuscola, e il Quick Menù del Meteo, che riporta "previsine" anziché "previsione"
> ![IMG_20210312_210714](https://user-images.githubusercontent.com/64266967/110993249-56783f00-8377-11eb-8613-b4faf0485b64.jpg)
> ![IMG_20210312_210734](https://user-images.githubusercontent.com/64266967/110993251-57a96c00-8377-11eb-8829-cf7ace546358.jpg)
> ![IMG_20210312_210754](https://user-images.githubusercontent.com/64266967/110993252-57a96c00-8377-11eb-9ba2-9932998205e8.jpg)

Previsine e MArzo, fix applicato, apparirà nelle prissme 1/2 build

**Comment by BIOLorenz** [comment]
> Buongiorno,
> Se posso segnalo anche un piccolissimo errore nel popup di connessione della Mi air 2.
> ![photo5954272411698443467](https://user-images.githubusercontent.com/51385837/111621413-41bd0080-87e8-11eb-85e2-ad61608f74a1.jpg)
> 
> Inoltre, se vi può essere utile, qualche mese fa avevo aperto un thread con alcune segnalazioni di errori/miglioramenti. Alcune di esse sono già state segnalate anche in questo thread.
> 
> Grazie per il vostro lavoro.

Questo l'ho sistemato ora, come gli altri fix lo vedrai tra 1/2 build

**Comment by BIOLorenz** [comment]
> Altro bug per quanto riguarda il Mi Cloud: non c'è abbastanza spazio per tutto il testo nel bottone. Lascerei semplicemente "Pausa" o "Metti in pausa".
> 
> Questo si verifica quando la galleria sta venendo sincronizzata con il cloud.
> 
> Immagine
> ![IMG_20210225_132418.jpg](https://user-images.githubusercontent.com/67104846/109156654-60902000-7771-11eb-9457-f6cb2f5ca674.jpg)
> 
> Chiedo scusa per lo spam e i numerosi problemi riportati, ho installato la Xiaomi.eu da circa due settimane e queste sono tutte cose che trovo con un normale utilizzo quotidiano. Grazie mille per il vostro impegno nel progetto!

Fix Applicato

**Comment by BIOLorenz** [comment]
> Trovati altri due.
> Entrambi sono nell'opzione "Trova Dispositivo" del Mi Cloud, accessibile dalle impostazioni, anche se credo queste stringhe siano usate anche altrove poiché sono molto generiche.
> 
> Il primo problema è quando si tenta di disattivare il tracciamento del dispositivo. La seconda opzione letteralmente non ha senso: cosa significa "Disattiva non presente"? quando lo clicco, viene disattivato senza problemi.
> 
> Immagine
> ![Screenshot_2021-02-25-00-53-40-601_com.miui.cloudservice.jpg](https://user-images.githubusercontent.com/67104846/109082488-626fca00-7704-11eb-8c01-a94522ea1543.jpg)
> 
> Il secondo problema è nel "footer" che si legge quando l'opzione è attivata:
> 
> "here" dovrebbe essere tradotto con "qui", e la frase dovrebbe essere ".... i dettagli qui", non ".... i dettagli SU qui".
> 
> Immagine
> ![Screenshot_2021-02-25-00-54-40-147_com.miui.cloudservice.jpg](https://user-images.githubusercontent.com/67104846/109082619-9c40d080-7704-11eb-9630-7767a0787c50.jpg)

Fixato ;)

**Comment by dgardina** [comment]
Buongiorno, ho notato che nella versione 21.4.7 la modalità "Ritratto" è stata tradotta con "Verticale".. ok che in inglese si usa "portrait/landscape", ma personalmente ci ho messo un po' a capire cos'era questa modalità "Verticale".. se potete correggere, grazie..

**Comment by BIOLorenz** [comment]
Fix in corso effettuati in 142a894d2e91c96c66d82570cd08db3d3dedab80 e a6a316b40a61ae680c79820ed612ee32685550cc

**Comment by BIOLorenz** [comment]
~~Problema 1 / Problem 1
 Il testo della modalità "silenziosa" va a capo per un singolo carattere, ed è brutto. I miei consigli sono:~~
 
~~tenere come testo "Silenz." con il punto finale;
metterlo in inglese, ovvero "Silent", anche se sarebbe errato perché stiamo parlando della versione italiana;
usare una sigla come "ND" (DND in inglese) per "Non disturbare", del tipo "SLZ".~~
 
 ~~Problema 2 / Problem 2
 Nell'app "schermo acceso", le ore e i minuti non sono separati da uno spazio. Questo appare sia nell'intestazione che nella lista app.
 In the "screen time" app, hours and minutes are not separated by space. This happens both in the header and in the app list.~~

Fix applicato e risolto nella build 21.4.14

**Comment by BIOLorenz** [comment]
~~Se possibile, farei un'ulteriore modifica.
Nell'app Orologio, quando si tocca su una sveglia.
Modificherei "Impostazioni addizionali" con semplicemente "Impostazioni", dato che il testo non ci sta nella casella e comunque "addizionali" è ridondante.~~

Fix applicato

**Comment by BIOLorenz** [comment]
~~Se non esiste già una traduzione, personalmente scriverei:
 

ND è attivo / Non disturbare è attivo / Non disturbare
Chiamate e notifiche saranno silenziate.
<Spegni> oppure <Disattiva>~~

Fix applicato e risolto nella build 21.4.14

**Comment by BIOLorenz** [comment]
~~Altro piccolo errore: quando si disattiva la modalità silenziosa, appare una notifica che dice "ND attivato. Suonerie per le chiamate e notifiche silenziate." Invece dovrebbe dire "Silenzioso attivato".~~

Fix applicato e risolto nella build 21.4.14

**Comment by BIOLorenz** [comment]
~~Segnalo due problemi di traduzione:~~
~~1. Suoni di notifica animali~~
~~Impostazioni~~ > ~~Suoni e vibrazione~~ > ~~Notifiche~~
~~Quando si impostano i suoni di notifica naturali alcuni nomi di animali sono tradotti, altri no. Per esempio "Cheetah" (Ghepardo) o "Hippo" (Elefante)
(anche nelle immagini sono solo alcuni esempi, non tutti gli errori)~~

Fix applicato e risolto nella build 21.4.14

~~2. Google Home sul control center~~
~~Ho scaricato google home e mi è apparso questo riquadro sul control center ma la frase non è tradotta... dovrebbe essere "Scegli un'applicazione per controllare la tua smart home"~~

Fix applicato

**Comment by BIOLorenz** [comment]
~~Aggiungerei che nella descrizione in alto la frase è spezzata a metà: "Puoi aggiungere fino..."~~

Fix applicato e risolto nella build 21.4.14

**Comment by BIOLorenz** [comment]
> Trovati altri due.
> Entrambi sono nell'opzione "Trova Dispositivo" del Mi Cloud, accessibile dalle impostazioni, anche se credo queste stringhe siano usate anche altrove poiché sono molto generiche.

>~~ Il primo problema è quando si tenta di disattivare il tracciamento del dispositivo. La seconda opzione letteralmente non ha senso: cosa significa "Disattiva non presente"? quando lo clicco, viene disattivato senza problemi.~~

> ~~Il secondo problema è nel "footer" che si legge quando l'opzione è attivata:~~
> 
>~~"here" dovrebbe essere tradotto con "qui", e la frase dovrebbe essere ".... i dettagli qui", non ".... i dettagli SU qui".~~

Fix applicato e risolto nella build 21.4.14

**Comment by BIOLorenz** [comment]
>~~Trovato altro problema nel control center... La data si spezza su due linee e quindi sposta anche lo spacing dei bottoni affianco.~~
> ~~Ovviamente il suggerimento è di abbreviare:~~
> 

~~Gio 25 Feb~~


Fix applicato

**Comment by BIOLorenz** [comment]
> ~~Altro bug per quanto riguarda il Mi Cloud: non c'è abbastanza spazio per tutto il testo nel bottone. Lascerei semplicemente "Pausa" o "Metti in pausa".~~

Fix applicato e risolto nella build 21.4.14

**Comment by BIOLorenz** [comment]
>~~Altro problema... Il nome del mese di Marzo ha anche la A maiuscola. Questo accade in diversi punti: le notifiche, il widget meteo, il control center...~~

Fixato

**Comment by BIOLorenz** [comment]
>~~Segnalo alcuni errori di traduzione, come il formato della data nel Control Center, il mese di Marzo che ha la A maiuscola, e il Quick Menù del Meteo, che riporta "previsine" anziché "previsione"~~

Fixato

**Comment by BIOLorenz** [comment]
> Buongiorno,
> Se posso segnalo anche un piccolissimo errore nel popup di connessione della Mi air 2.
> ![photo5954272411698443467](https://user-images.githubusercontent.com/51385837/111621413-41bd0080-87e8-11eb-85e2-ad61608f74a1.jpg)
> 
> Inoltre, se vi può essere utile, qualche mese fa avevo aperto un thread con alcune segnalazioni di errori/miglioramenti. Alcune di esse sono già state segnalate anche in questo thread.
> 
> Grazie per il vostro lavoro.

Ciao,
questa issue dovresti verificarla tu con la build 21.4.14 o con la prossima stable in quanto non possiedo le Mi Air :)

**Comment by BIOLorenz** [comment]
Tutte le issue sono state risolte con gli ultimi commit
c6a634bf257f52ec48f9580cc855b1fb2847c2de 142a894d2e91c96c66d82570cd08db3d3dedab80 a6a316b40a61ae680c79820ed612ee32685550cc e0083ef1065759879be4e624fc95384336c8d500 

Ho sistemato anche l'integrazione con il mio Crowdin personale e Github in modo da velocizzare le operazioni!
Se notate altre anomalie aprite una nuova issue e se vi va offritemi una birra o un caffè (virtuali, tanto in Italia è tutto chiuso) cliccando su sponsor in alto a destra! 😃

**Comment by mind-overflow** [comment]
grazie mille! ho notato altri problemini nuovi delle scorse build, ma aspetto di installare l'aggiornamento prima di riportarli. preferisci una issue separata per ognuno, oppure come questa una unica? perché teoricamente con i commit e la chiusura automatica sarebbe meglio avere issue separate.

ottimo lavoro :)

**Comment by BIOLorenz** [comment]
Ciao!
Guarda, è indifferente, di solito tendo a tradurre altre stringhe oltre a sistemare quelle mal tradotte, quindi issue unica o thread van bene uguale
