### ISSUE TITLE
Piccola correzione nel mese.

### ISSUE THREAD

**Issue by Kekko01** [nathan990315/MIUI_12_Italy#35]
È possibile correggere la scritta MArzo con Marzo?
![photo_2021-03-15_10-14-26](https://user-images.githubusercontent.com/41902476/111130341-6494ae00-8577-11eb-9efc-eccff3e417c8.jpg)

**Comment by VforVolcano** [comment]
Qui si trova l'errore:

https://github.com/nathan990315/MIUI_12_Italy/blob/29602bb1329678b377c281b10102487e1c0725c5/Italian/main/MiuiAod.apk/res/values-it/strings.xml#L318
