### ISSUE TITLE
Disinstallazione app da louncher di sistema

### ISSUE THREAD

**Issue by Amro1002** [nathan990315/MIUI_12_Italy#36]
Ci sono dei problemi con il louncher di sistema.
Uso la versione con il cassetto app e gesture. 
Se tengo premuta una app per disintallarla, mi fa l'animazione, ma non la rimuove.
Ci sono poi alcune app che non vengono visualizzate.
Mi spiego, avevo genshin impact, l'ho aggiornato e mi è scomparso dal cassetto delle app.
Se vado sul play store posso avviarlo quindi è. Ancora presente nel telefono.
Succede con diverse app, per il momento me ne sono accorto solo con genshin e con word of tanks.
Grazie dell'attenzione

**Comment by Amro1002** [comment]
Lascio il link del video in cui mostro i 2 problemi riscontrati[Link di mega](https://mega.nz/file/Xl0wRCTL#3jPCBZoCqQftTOTkiD9UWkWt9ly20ygTdpnv23Hmys0)

**Comment by BIOLorenz** [comment]
Ciao,
questa sezione è relativa solo ai bug di traduzione, non a quelli  di sistema.
Ti consiglio di aprire un post su xiaomi.eu oppure su c.mi.com per segnalare il bug.

Grazie!
