### ISSUE TITLE
Problema traduzione Limitazione notifiche

### ISSUE THREAD

**Issue by davidep85** [nathan990315/MIUI_12_Italy#37]
Ciao a tutti, possiedo Xiaomi Mi 11 con Miui 12.5 21.3.17.

Quando compare una notifica, se nella barra delle notifiche si tiene premuto, compaiono sotto delle icone tra cui a sinistra quella con la campanella. La traduzione che c'è scritta sotto è "Concorda e Scarica" ma credo che qua ci sia il menu di limitazione delle notifiche.

É necessario aggiornare la traduzione?

**Comment by BIOLorenz** [comment]
Ciao, si confermo.
Prendo in carico in quanto ho iniziato la correzione di alcune stringhe. Vedrai il problema risolto nelle prossime build ;)

**Comment by davidep85** [comment]
Grazie mille, ne ho viste altre ma le inserisco appena le ribecco!

**Comment by BIOLorenz** [comment]
Fix effettuato in 142a894d2e91c96c66d82570cd08db3d3dedab80 e a6a316b40a61ae680c79820ed612ee32685550cc se ne trovi altre apri una nuova issue relativa così teniamo traccia :)
