### ISSUE TITLE
Traduzioni Mancanti

### ISSUE THREAD

**Issue by francescobenenati** [nathan990315/MIUI_12_Italy#38]
Buongiorno, 
Segnalo una traduzione mancante nel pop-up che appare quando la batteria scende sotto una certa soglia. La versione che sto usando al momento è la 21.3.17 su MI 10.
"Turn on Battery Saver To Add" dovrebbe essere "_Attiva Risparmio Batteria per aggiungere_" o "_Attiva Risparmio Energetico per aggiungere_"
Allego screenshot :
![photo5992253898418664476](https://user-images.githubusercontent.com/51385837/113273297-cd508a00-92dc-11eb-84ad-12b2e430c2da.jpg)
Grazie come sempre per il vostro lavoro.

**Comment by francescobenenati** [comment]
Ho notato che questa settimana (21.04.08) sono cambiate un sacco di stringhe e la traduzione ne ha chiaramente risentito. Aggiungo quelle che ho visto non essere state segnalate in altri issues.

1. All'attivazione/disattivazione del silenzioso appare: _Silent Mode is On / Silent Mode is Off_ dovrebbe essere **Silenzioso attivato o Modalità silenziosa attivata**.
2. Alla disattivazione del non disturbare appare: _Calls and Notifications won't be silenced anymore_ dovrebbe essere: **Le chiamate e le notifiche non saranno più silenziate**.
3. Alla voce notifiche e centro di controllo -> Area di Notifica è tornato nuovamente "_Dispositivo MIUI_" . 2 build fa era già stato corretto con la stringa giusta, ovvero: **Android**.
4. Alla voce notifiche e centro di controllo -> Barra di stato: _Test Accensione_ dovrebbe essere **Icona Batteria**
5. Alla voce Schermo sono presenti dei caratteri cinesi alla fine della pagina.

**Comment by BIOLorenz** [comment]
> Ho notato che questa settimana (21.04.08) sono cambiate un sacco di stringhe e la traduzione ne ha chiaramente risentito. Aggiungo quelle che ho visto non essere state segnalate in altri issues.
> 
> 1. All'attivazione/disattivazione del silenzioso appare: _Silent Mode is On / Silent Mode is Off_ dovrebbe essere **Silenzioso attivato o Modalità silenziosa attivata**.
> 2. Alla disattivazione del non disturbare appare: _Calls and Notifications won't be silenced anymore_ dovrebbe essere: **Le chiamate e le notifiche non saranno più silenziate**.
> 3. Alla voce notifiche e centro di controllo -> Area di Notifica è tornato nuovamente "_Dispositivo MIUI_" . 2 build fa era già stato corretto con la stringa giusta, ovvero: **Android**.
> 4. Alla voce notifiche e centro di controllo -> Barra di stato: _Test Accensione_ dovrebbe essere **Icona Batteria**
> 5. Alla voce Schermo sono presenti dei caratteri cinesi alla fine della pagina.
> 6. Alla voce Suoni e Vibrazione: _MEDIA_ è tutto in maiuscolo, meglio se fosse **Media**. In generale in questo menu sono presenti numerose descrizioni in inglese.

Fix effettuato in 142a894d2e91c96c66d82570cd08db3d3dedab80 e a6a316b40a61ae680c79820ed612ee32685550cc

**Comment by BIOLorenz** [comment]
> Buongiorno,
> Segnalo una traduzione mancante nel pop-up che appare quando la batteria scende sotto una certa soglia. La versione che sto usando al momento è la 21.3.17 su MI 10.
> "Turn on Battery Saver To Add" dovrebbe essere "_Attiva Risparmio Batteria per aggiungere_" o "_Attiva Risparmio Energetico per aggiungere_"
> Allego screenshot :
> ![photo5992253898418664476](https://user-images.githubusercontent.com/51385837/113273297-cd508a00-92dc-11eb-84ad-12b2e430c2da.jpg)
> Grazie come sempre per il vostro lavoro.

Questo lo gestirò domani probabilmente, devo ancora arrivare a quel file.

**Comment by BIOLorenz** [comment]
Tutte le issue sono state risolte con gli ultimi commit
c6a634bf257f52ec48f9580cc855b1fb2847c2de 142a894d2e91c96c66d82570cd08db3d3dedab80 a6a316b40a61ae680c79820ed612ee32685550cc e0083ef1065759879be4e624fc95384336c8d500 

Ho sistemato anche l'integrazione con il mio Crowdin personale e Github in modo da velocizzare le operazioni!
Se notate altre anomalie aprite una nuova issue e se vi va offritemi una birra o un caffè (virtuali, tanto in Italia è tutto chiuso) cliccando su sponsor in alto a destra! 😃
