### ISSUE TITLE
Miui 12.5.3 errori traduzione

### ISSUE THREAD

**Issue by davidep85** [nathan990315/MIUI_12_Italy#39]
Ciao a tutti, sembra che la Miui 12.5.3 sia uscita un po' maluccio con le traduzioni, di seguito alcune segnalazioni :-)

1. Barra delle notifiche, widget dati. É stato tradotto come "Statistiche traffico". Dovrebbe essere "Dati mobili"
2. Barra delle notifiche, widget suoneria/silenzioso. É stato tradotto come "Muto". Dovrebbe essere "Suoneria"
3. Barra delle notifiche, widget gps. É stato tradotto come "Piattaforma". Dovrebbe essere "Posizione"
4. In Galleria "ALBUM" è tutto in maiuscolo. Dovrebbe essere "Album"
5. In SIM e reti mobili non è tradotto in italiano "Use mobile data during 4G calls on the secondary SIM" e relativa descrizione
6. Nelle impostazioni di schermata di blocco il timeout schermo è stato tradotto come "Dormi". Dovrebbe essere "Timeout" o "Timeout schermo"
7. Nelle impostazioni del suono non è tradotto in italiano "Notify about calls"
8. Nelle impostazioni del suono, in effetti sonori è presenta una scritta ancora in cinese (suppongo sia riferita all'ottimizzazione dell'audio Harman Kardon)
9. Nelle impostazioni del suono, in impostazioni addizionali, la label "FLUSSO" è tutta maiuscola. Dovrebbe essere "Flusso"
9. Nella fotocamera non è tradotto in italiano "Auto night mode" e relativa descrizione
10. Nella fotocamera la modalità ritratto è tradotta come "Verticale"
11. Nella fotocamera la modalità a schermo intero è stata tradotta come "Completa"
12. Nelle notifiche quando premi per limitarla, la traduzione è "Consenti". É corretta? Forse metterei "Limita" o "Mostra notifiche" o semplicemente "Notifiche"

Se vedo altro vi aggiorno, ciaooooo

**Comment by francescobenenati** [comment]
Ne aggiungo qualcuna pure io, ho notato che questa settimana sono cambiate un sacco di stringhe e la traduzione ne ha chiaramente risentito.

1. All'attivazione/disattivazione del silenzioso appare: _Silent Mode is On_  / _Silent Mode is Off_ dovrebbe essere Silenzioso attivato o Modalità silenziosa attivata.
2. Alla disattivazione del non disturbare appare: _Calls and Notifications won't be silenced anymore_ dovrebbe essere: **Le chiamate e le notifiche non saranno più silenziate**.
3. Alla voce notifiche e centro di controllo -> Area di Notifica è tornato nuovamente "_Dispositivo MIUI_" . 2 build fa era già stato corretto con la stringa giusta, ovvero: **Android**.
4. Alla voce notifiche e centro di controllo -> Barra di stato: _Test Accensione_ dovrebbe essere **Icona Batteria**
5. Alla voce Schermo sono presenti dei caratteri cinesi alla fine della pagina.

**Comment by BIOLorenz** [comment]
Ciao!
Grazie per le segnalazioni, ho integrato github con il sito che uso per le traduzioni quindi si è fatta un po' di confusione.
Sto anche modificando alcune traduzioni storiche che vanno riadattate.

Grazie per le segnalazioni, sono state sistemate le vedrai nelle prossime build.

> Nelle notifiche quando premi per limitarla, la traduzione è "Consenti". É corretta? Forse metterei "Limita" o "Mostra notifiche" o semplicemente "Notifiche"

In questa ho scritto "Limita", in inglese la traduzione è "Allow" per quello c'è permetti.

**Comment by BIOLorenz** [comment]
> Ciao a tutti, sembra che la Miui 12.5.3 sia uscita un po' maluccio con le traduzioni, di seguito alcune segnalazioni :-)
> 
~~> 1. Barra delle notifiche, widget dati. É stato~~ ~~tradotto come "Statistiche traffico". Dovrebbe essere "Dati mobili"
> 2. Barra delle notifiche, widget suoneria/silenzioso. É stato tradotto come "Muto". Dovrebbe essere "Suoneria"
> 3. Barra delle notifiche, widget gps. É stato tradotto come "Piattaforma". Dovrebbe essere "Posizione"
> 4. In Galleria "ALBUM" è tutto in maiuscolo. Dovrebbe essere "Album"~~
> 5. In SIM e reti mobili non è tradotto in italiano "Use mobile data during 4G calls on the secondary SIM" e relativa descrizione
~~> 6. Nelle impostazioni di schermata di blocco il timeout schermo è stato tradotto come "Dormi". Dovrebbe essere "Timeout" o "Timeout schermo"
> 7. Nelle impostazioni del suono non è tradotto in italiano "Notify about calls"~~
> 8. Nelle impostazioni del suono, in effetti sonori è presenta una scritta ancora in cinese (suppongo sia riferita all'ottimizzazione dell'audio Harman Kardon)
> 9. Nelle impostazioni del suono, in impostazioni addizionali, la label "FLUSSO" è tutta maiuscola. Dovrebbe essere "Flusso"
> 9. Nella fotocamera non è tradotto in italiano "Auto night mode" e relativa descrizione
> ~~10. Nella fotocamera la modalità ritratto è tradotta come "Verticale"
> 11. Nella fotocamera la modalità a schermo intero è stata tradotta come "Completa"~~
> 12. Nelle notifiche quando premi per limitarla, la traduzione è "Consenti". É corretta? Forse metterei "Limita" o "Mostra notifiche" o semplicemente "Notifiche"
> 
> Se vedo altro vi aggiorno, ciaooooo

I punti non barrati sono quelli in cui potrebbe non essersi applicata la traduzione.
Attendo comunque una conferma :)

**Comment by BIOLorenz** [comment]
Fix applicati
