### ISSUE TITLE
Bug Traduzioni 21.4.21

### ISSUE THREAD

**Issue by francescobenenati** [nathan990315/MIUI_12_Italy#40]
Buonasera,
Faccio una lista dei problemi di traduzione riscontrati nella build 21.4.21 su mi 10.

1. La stringa per sbloccare un numero di telefono o un contatto è sbagliata, compare infatti "_Annulla Schermata_" al posto di "**Sblocca Contatto**". 

2. Nelle categorie delle notifiche delle Applicazioni come ad esempio Notifiche Gruppi di Whatsapp compare "_Test Vibrazione_" al posto di "**Consenti Vibrazione**" o semplicemente "**Vibrazione**". Vedi Screenshot

![2021-04-22 21 38 30](https://user-images.githubusercontent.com/51385837/115778473-06998880-a3b7-11eb-979a-da0ae90f976f.jpg)

3. In Password e sicurezza -> Blocco schermo: All’inserimento Password compare una stringa con tag html. Vedi screenshot

![2021-04-22 21 38 38](https://user-images.githubusercontent.com/51385837/115778328-ccc88200-a3b6-11eb-9d81-29dba7286ee9.jpg)

4. Suoni e vibrazione: 
- Descrizione di Non disturbare: “_There’ll no Reminders for incoming calls and notifications_” dovrebbe essere: **Le chiamate e le notifiche verranno silenziate**.
- _Notify about calls_ dovrebbe essere “**Notifiche chiamate**”
- Menu di Notify about calls -> _From anyone_ dovrebbe essere “**Da tutti**”, _From Contacts only_ dovrebbe essere “**Solo dai contatti**”, _from starred Contacts only_ dovrebbe essere “**Solo dai contatti preferiti**”
- “_Promemoria chiamante ripetuti_” dovrebbe essere **Notifica chiamate ripetute**.
- Descrizione “Promemoria chiamante ripetuti”: _Ring or vibrate while receiving the second call from the same phone number within 15 minutes_ dovrebbe essere **Suona o vibra se lo stesso numero di telefono chiama due volte in 15 minuti.**

5. Applicazioni -> Gestione Applicazioni: Nella lista delle app le opzioni per ordinare le app sono in inglese. Sono: _sort by status, sort by app name, sort by frequency, sort by used storage, sort by installation time._
Vedi Screenshot:

![2021-04-22 22 20 05](https://user-images.githubusercontent.com/51385837/115780385-64c76b00-a3b9-11eb-8d1b-ceed83670135.jpg)

6. Il nuovo slider per il timer del silenzioso è tradotto male. Sono entrambi tradotti come _Timer ND_, uno dovrebbe essere **Timer Silenzioso**
![photo5771516360638183420](https://user-images.githubusercontent.com/51385837/115870138-21174480-a43f-11eb-9746-1fa064b5aee3.jpg)

7. App Meteo: _Light Rain_ dovrebbe essere **Pioggia Leggera**
![photo_2021-04-24_16-44-34](https://user-images.githubusercontent.com/51385837/115962651-bd634900-a51c-11eb-8637-f7242a0884d3.jpg)

Aggiornerò il post se ne dovessi trovare delle altre, nel frattempo grazie come sempre :)

**Comment by BIOLorenz** [comment]
Ciao,
tutti i fix applicati!

Per il punto 6 ho optato per la dicitura "Timer" e basta, lo spazio nel riquadro è poco e non c'è differenziazione nelle stringhe tra Silenzioso e non disturbare (la stringa inglese sarebbe "Slide to set Timer").

Troverai le correzioni nella prossima build :)
