### ISSUE TITLE
xiaomi mi 11 ultra riavvio continuo miui 12.5.2

### ISSUE THREAD

**Issue by studiosupreme7** [nathan990315/MIUI_12_Italy#43]
salve ,

stanotte il telefono mi 11 ultra si è aggiornato da miui 12.0.6 a miui 12.5.2, adesso il telefono si riavvia ogni volta che si apre qualche app che usa il gps, è inutilizzabile. solo disabilitando il gps il telefono non si riavvia.

[https://drive.google.com/file/d/1o7X3Q5a7FgKmd057IH_0LofJhY6YGsxr/view?usp=sharing](url)

PS: lo stà facendo a tutti quelli che hanno compratomil telefono sullo store ufficiale italiano.

come si risolve?  grazie

**Comment by BIOLorenz** [comment]
Ciao,
questa sezione serve esclusivamente per segnalare problemi di traduzione nella Xiaomi.eu

Per le problematiche indicate, ti conviene provare a scrivere nel forum MIUI c.mi.com oppure se hai la versione Xiaomi.eu nel forum relativo al tuo dispositivo.

Come consiglio personale, ti consiglio di effettuare un reset di fabbrica.
