### ISSUE TITLE
Nella sezione "Tipologia di rete preferita" ogni scritta e diversa

### ISSUE THREAD

**Issue by M4th12** [nathan990315/MIUI_12_Italy#54]
![Screenshot_2021-08-17-13-16-36-717_com android phone](https://user-images.githubusercontent.com/89078127/129717040-cfe83137-5875-4daf-8dc4-62961b281fad.jpg)
Informazioni: 
Dispositivo: Imi (Hmk30Pro)
Versione: 12.5.3 Stabile
Applicazione: Impostazioni (Impostazioni>SIM e Reti mobili>Impostazioni SIM>Tipologia di rete preferita) 
Suggerimento: 
Preferisci reti 5G
Preferisci reti 4G/LTE
Preferisci reti 3G
Preferisci reti 2G

**Comment by aScordino** [comment]
"Preferisci reti 2G" non avrebbe molto senso. Il resto è OK per me.
Fixato con il Pull Request #56

**Comment by BIOLorenz** [comment]
Grazie!
Fixed #56
