### ISSUE TITLE
Crash Impostazioni 

### ISSUE THREAD

**Issue by XNinfadoraX** [nathan990315/MIUI_12_Italy#55]
![Screenshot_2021-08-27-12-21-15-108_com android updater](https://user-images.githubusercontent.com/89638431/131112753-ce3cc24b-bfa7-4567-a74f-06ca3143d7db.jpg)
![IMG_20210827_122059](https://user-images.githubusercontent.com/89638431/131112758-4e816f76-417a-4741-91bf-1da5af2c9dbb.jpg)

Impostazioni non si apre e continua a Crashare.
Can't able to open Settings, always crash
 Mi 9 Lite

**Comment by BIOLorenz** [comment]
> Ci sono riuscita, ho risolto riflashando la rom da twrp :) grazie di nuovo a tutti :)

Fantastico!
Chiudo la issue.

Ciao e goditi la xiaomi.eu 😄
