### ISSUE TITLE
Menù principale impostazioni 

### ISSUE THREAD

**Issue by M4tth05** [nathan990315/MIUI_12_Italy#59]
Voce al femminile sulla sezione dell'always on display: spenta al posto di spento

**Comment by aScordino** [comment]
Ciao, penso di aver trovato l'errore. 
Però, per cortesia, la prossima volta faresti meglio a seguire le informazioni da darci, scritte su `README.md`:

> Descrivere nella sezione "Issues":
> - La problematica [Stringa in inglese, traduzione errata...]
> - In che applicazione è stata riscontrata
> - La versione della Xiaomi.eu utilizzata
> - Il dispositivo in cui si verifica l'errore
> - Allegare se possibile uno screenshot dell'errore
> - Fornire suggerimenti sulla traduzione

E grazie mille per aver segnalato l'issue 😃
