### ISSUE TITLE
Errore orologio doppio, c'è una k di troppo

### ISSUE THREAD

**Issue by soloxme** [nathan990315/MIUI_12_Italy#62]
![IMG_20210904_130719](https://user-images.githubusercontent.com/40915841/132092353-20d09ef4-3241-4d26-a40b-a08101df40af.jpg)

**Comment by soloxme** [comment]
La versione MIUI è la 21.9.1 il device è il MI11 ultra

**Comment by aScordino** [comment]
Ciao. Probabilmente questo è già stato fixato visto che non torvo nessuna referenza a "`doppiok`"  sulla repository. Aspetta per un prossimo update e ricontrolla.
