### ISSUE TITLE
String translate

### ISSUE THREAD

**Issue by Truciolo** [nathan990315/MIUI_12_Italy#63]
![IMG_20210919_104750](https://user-images.githubusercontent.com/44978412/133921283-0578cc24-1a31-4f56-9335-c6ef60d34ddb.jpg)

Errore di battitura su scelta modo 3G 

Xiaomi.eu.21.9.17
Impostazioni sim/tipologia rete preferita
Mi 10 pro

**Comment by nathan990315** [comment]
ok grazie correggerò la string a nella prossima versione

**Comment by aScordino** [comment]
Ciao, scusa per l'errore di battitura! :-(
Correggerò al piú presto. Grazie

**Comment by BIOLorenz** [comment]
Effettuato il merge #71
