### ISSUE TITLE
"Ferma" quando cerchi nelle impostazioni

### ISSUE THREAD

**Issue by jututt** [nathan990315/MIUI_12_Italy#8]
Sarebbe meglio "Annulla"

**Comment by nathangiovannini3** [comment]
Ciao hai riscontrato un problema di traduzione? Se si puoi indicare dove esattamente nelle impostazioni?

**Comment by Sventra** [comment]
> Ciao hai riscontrato un problema di traduzione? Se si puoi indicare dove esattamente nelle impostazioni?

Impostazioni>Cerca nelle impostazioni

Effettivamente "Ferma" è sbagliato visto che non si sta fermando niente, ma premendo quel tasto si Annulla la ricerca

**Comment by nathan990315** [comment]
Ok grazie cercherò di individuare la stringa incriminata e correggerla per la prossima settimana

**Comment by Sventra** [comment]
> Ok grazie cercherò di individuare la stringa incriminata e correggerla per la prossima settimana

<string name="wfd_menu_teardown">Ferma</string>

**Comment by BIOLorenz** [comment]
Ciao,
stringa modificata in "Annulla"
https://github.com/nathan990315/MIUI_12_Italy/commit/80edaf47be1b69439877a36d40858dae50187467

Grazie della segnalazione!
